name: Build and Publish Library

on:
  push:
    branches: main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3


      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.13
      - name: Install Angular CLI globally
        run: npm install -g @angular/cli
      - name: Install dependencies
        run: npm install

      - name: Build the library
        run: ng build blabib

      - name: Archive the build output
        uses: actions/upload-artifact@v3
        with:
          name: library-dist
          path: dist

      - name: Login to npm (if publishing publicly)
        run: |
          if [ ${{ secrets.GITHUB_TOKEN }} ]; then
            npm login
            echo "//registry.npmjs.org/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
            echo "Successfully logged in to npm registry"
          else
            echo "Skipping npm login as GITHUB_TOKEN is not provided"
          fi

      - name: Publish the library (if publishing publicly)
        uses: actions/upload-artifact@v3
        with:
          name: library-npm
          path: ~/.npmrc

      - name: Deploy to npm (if publishing publicly)
        run: |
          if [ ${{ secrets.GITHUB_TOKEN }} ]; then
            npm publish
            echo "Successfully published library to npm"
          else
            echo "Skipping npm publish as GITHUB_TOKEN is not provided"
          fi
